### ISSUE TITLE
7-to-8 repo migration failing with null Bootstrappers

### ISSUE THREAD

**Issue by pontiyaraja** [ipfs/fs-repo-migrations#107]
Please refer here :
https://github.com/ipfs/go-ipfs/issues/7676

Initializing daemon...
go-ipfs version: 0.6.0-53971d664
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Running: /var/folders/yl/5sr1t26d27ddbrx5mcfqr48r0000gn/T/go-ipfs-migrate437691780/fs-repo-migrations -to 10 -y
Found fs-repo version 7 at /Users/pandiyarajaramamoorthy/.ipfs
===> Running migration 7 to 8...
applying 7-to-8 repo migration
locking repo at "/Users/pandiyarajaramamoorthy/.ipfs"
  - verifying version is '7'
> Upgrading config to new format
Bootstrap field missing or of the wrong type
Nothing to migrate
updated version file
===> Migration 7 to 8 succeeded!
===> Running migration 8 to 9...
applying 8-to-9 repo migration
updated version file
===> Migration 8 to 9 succeeded!
===> Running migration 9 to 10...
applying 9-to-10 repo migration
locking repo at "/Users/pandiyarajaramamoorthy/.ipfs"
  - verifying version is '9'
> Upgrading config to new format
ipfs migration:  migration 9 to 10 failed: unexpected end of JSON input
  => Failed: /var/folders/yl/5sr1t26d27ddbrx5mcfqr48r0000gn/T/go-ipfs-migrate437691780/fs-repo-migrations -to 10 -y
The migrations of fs-repo failed:
  migration failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration failed: exit status 1

@Stebalien 
@mikeal 
@hsanjuan

**Comment by aschmahmann** [comment]
There was a bug introduced in #97 where we broke migrations with nil (instead of `[]`) Bootstrappers by returning nil because then we don't write anything to the output file. We can fix this by doing `out.Write(data); return nil` instead.

**Comment by pontiyaraja** [comment]
Thank you @aschmahmann

**Comment by aschmahmann** [comment]
No problem, a binary release should be out on dist.ipfs.io later this week or you can just build the source on your own
