### ISSUE TITLE
Datastore: key not found

### ISSUE THREAD

**Issue by Rutvik1995** [ipfs/fs-repo-migrations#109]
There was some kind of upgradation or migration. When I starting my IPFS daemon server. I am getting datastore not found error. Please can one can help me solving this issue.

---

Rutviks-MacBook-Pro-2:~ rutvikpatel$ ipfs daemon 
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Running: /var/folders/7y/pyj6j88x6c37113c_lfnsmjc0000gn/T/go-ipfs-migrate054774885/fs-repo-migrations -to 10 -y
Found fs-repo version 2 at /Users/rutvikpatel/.ipfs
===> Running migration 2 to 3...
applying 2-to-3 repo migration
locking repo at "/Users/rutvikpatel/.ipfs"
  - verifying version is '2'
beginning pin transfer
  - opening datastore at "/Users/rutvikpatel/.ipfs"
  - created version 3 pinner
  - loading recursive pins
ipfs migration:  migration 2 to 3 failed: **datastore: key not found**
  => Failed: /var/folders/7y/pyj6j88x6c37113c_lfnsmjc0000gn/T/go-ipfs-migrate054774885/fs-repo-migrations -to 10 -y
The migrations of fs-repo failed:
  migration failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration failed: exit status 1

**Comment by aschmahmann** [comment]
@Rutvik1995 what version of go-ipfs are you upgrading from, and do you mind posting your config (make sure to remove your private key)?

**Comment by Rutvik1995** [comment]
@aschmahmann I am pretty new to IPFS and can guide me tell me how do I can see my config file on mac. Earlier everything was working file. When I started my ipfs daemon error occur and told me go to some git repo for migration. I was still getting error version 10 but its still 2 type of error.

**Comment by aschmahmann** [comment]
The config file lives in YourRepo/config (e.g. ~/.ipfs/config). You can also see it using `ipfs config show` (assuming your older version of go-ipfs supports that command).

It looks like you've recently upgraded from a very old version of go-ipfs (e.g. 4-5 years old). Which version of go-ipfs was it (you can tell by running ipfs version using your old go-ipfs binary)?

**Comment by Rutvik1995** [comment]
Hey @aschmahmann Thank you guiding me
The IPFS config commands works for me and I am getting this thing.

{
  "API": {
    "HTTPHeaders": null
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx"
  ],
  "Datastore": {
    "GCPeriod": "1h",
    "Path": "/Users/rutvikpatel/.ipfs/datastore",
    "StorageGCWatermark": 90,
    "StorageMax": "10GB",
    "Type": "leveldb"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Gateway": {
    "HTTPHeaders": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "Qmf4vaWQr2yyhwm7zTGtB6j853SjNTeqvs8fUfSSAuP6Dc"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "SupernodeRouting": {
    "Servers": [
      "/ip4/104.236.176.52/tcp/4002/ipfs/QmXdb7tWTxdFEQEFgWBqkuYSrZd3mXrC7HxkD4krGNYx2U",
      "/ip4/104.236.179.241/tcp/4002/ipfs/QmVRqViDByUxjUMoPnjurjKvZhaEMFDtK35FJXHAM4Lkj6",
      "/ip4/104.236.151.122/tcp/4002/ipfs/QmSZwGx8Tn8tmcM4PtDJaMeUQNRhNFdBLVGPzRiNaRJtFH",
      "/ip4/162.243.248.213/tcp/4002/ipfs/QmbHVEEepCi7rn7VL7Exxpd2Ci9NNB6ifvqwhsrbRMgQFP",
      "/ip4/128.199.219.111/tcp/4002/ipfs/Qmb3brdCYmKG1ycwqCbo6LUwWxTuo3FisnJV2yir7oN92R",
      "/ip4/104.236.76.40/tcp/4002/ipfs/QmdRBCV8Cz2dGhoKLkD3YjPwVFECmqADQkx5ZteF2c6Fy4",
      "/ip4/178.62.158.247/tcp/4002/ipfs/QmUdiMPci7YoEUBkyFZAh2pAbjqcPr7LezyiPD2artLw3v",
      "/ip4/178.62.61.185/tcp/4002/ipfs/QmVw6fGNqBixZE4bewRLT2VXX7fAHUHs8JyidDiJ1P7RUN"
    ]
  },
  "Swarm": {
    "AddrFilters": null
  },
  "Tour": {
    "Last": ""
  },
  "Version": {
    "AutoUpdate": "minor",
    "Check": "error",
    "CheckDate": "0001-01-01T00:00:00Z",
    "CheckPeriod": "172800000000000",
    "Current": "0.3.11"
  }
}

When I type ipfs version I got 
**ipfs version 0.7.0**

I think old one was something like 0.3.0.

The issue is something link with Datastore I accidentally changed to "Path": "/Users/rutvikpatel/.ipfs/datastore". Initially it was something else which came by default.

**Comment by Rutvik1995** [comment]
Hey @aschmahmann,  Thank You for your above suggestion and reviewing my problem. Sorry that I was not able to explain problem is clear and good manner. 

I removed the old directory by this command 
 $ rm -R  ~/.ipfs/

Then started run 
$ ipfs init  
command 

then started 
$ipfs daemon 
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/192.168.11.183/tcp/4001
Swarm listening on /ip4/192.168.11.183/udp/4001/quic
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/192.168.11.183/tcp/4001
Swarm announcing /ip4/192.168.11.183/udp/4001/quic
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080

The IPFS server successfully start running

**Comment by aschmahmann** [comment]
@Rutvik1995 glad you're up and running with the latest go-ipfs. 

Thanks for the report it seems likely that manually changing the datastore path was causing you problems. If anyone else runs into something similar they can reopen or create a new issue.
