### ISSUE TITLE
One more fs-repo-migrations issue

### ISSUE THREAD

**Issue by Centaro0** [ipfs/fs-repo-migrations#113]
Hello everyone, I have had this problem for a couple of months now, and I have tried looking for possible solutions, but I didn't really find anything :man_shrugging: Does anyone know what the problem might be?

Initializing daemon...
go-btfs version: 1.4.0-68f24b1
Repo version: 10
System version: amd64/linux
Golang version: go1.14.9
Found outdated fs-repo, migrations need to be run.
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Failed to download fs-repo-migrations.
The migrations of fs-repo failed:
  failed to download latest fs-repo-migrations: exec: "sh": executable file not found in $PATH
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: failed to download latest fs-repo-migrations: exec: "sh": executable file not found in $PATH

Thanks in advance for your support :peace_symbol: :heart:

**Comment by aschmahmann** [comment]
This error is being triggered by btfs trying to use fs-repo-migrations. The maintainers of this repo do not support btfs or know what they're doing with fs-repo-migrations.
