### ISSUE TITLE
repo not on default path

### ISSUE THREAD

**Issue by rjy7wb** [ipfs/fs-repo-migrations#114]
I have a repo that is on a separate drive and I see no options to specify a separate path, this also ignores the $IPFS_PATH environment variable

**Comment by aschmahmann** [comment]
@rjy7wb can you give more information? What version of fs-repo-migrations are you using, what OS are you using?

Setting IPFS_PATH works for me just fine on Linux (Ubuntu 20.04.1) using the latest fs-repo-migrations (v1.7.0)

**Comment by rjy7wb** [comment]
sorry i think i solved this by using the tool directly, it was not working when being invoked through go-ipfs after updating to a version that required an update to the fs.

**Comment by gammazero** [comment]
@rjy7wb Sounds like this is resolved. If so, please close this issue.
