### ISSUE TITLE
upgrade happen error

### ISSUE THREAD

**Issue by Shercode** [ipfs/fs-repo-migrations#123]
2021-03-02T02:19:31.103Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.8.0
Repo version: 11
System version: amd64/windows
Golang version: go1.15.8
Found outdated fs-repo, migrations need to be run.
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Failed to download fs-repo-migrations.
The migrations of fs-repo failed:
  failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmYRLRDKobvg1AXTGeK5Xk6ntWTsjGiHbyNKhWfz7koGpa/fs-repo-migrations/versions": dial tcp 64.13.192.76:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
 

 Error: failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmYRLRDKobvg1AXTGeK5Xk6ntWTsjGiHbyNKhWfz7koGpa/fs-repo-migrations/versions": dial tcp 64.13.192.76:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 

 Command failed with exit code 1: D:\ProgramFiles_x86\IPFS-Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe daemon --migrate --enable-gc --routing dhtclient
Error: failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmYRLRDKobvg1AXTGeK5Xk6ntWTsjGiHbyNKhWfz7koGpa/fs-repo-migrations/versions": dial tcp 64.13.192.76:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Initializing daemon...
go-ipfs version: 0.8.0
Repo version: 11
System version: amd64/windows
Golang version: go1.15.8
Found outdated fs-repo, migrations need to be run.
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Failed to download fs-repo-migrations.
The migrations of fs-repo failed:
  failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmYRLRDKobvg1AXTGeK5Xk6ntWTsjGiHbyNKhWfz7koGpa/fs-repo-migrations/versions": dial tcp 64.13.192.76:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
 

    at makeError (D:\ProgramFiles_x86\IPFS-Desktop\resources\app.asar\node_modules\ipfsd-ctl\node_modules\execa\lib\error.js:59:11)
    at handlePromise (D:\ProgramFiles_x86\IPFS-Desktop\resources\app.asar\node_modules\ipfsd-ctl\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-02T02:24:25.943Z error: [updater] Error: net::ERR_CONNECTION_RESET

**Comment by aschmahmann** [comment]
This seems to be the same error as https://github.com/ipfs-shipyard/ipfs-desktop/issues/1773, i.e. that your ISP/network is blocking access to the HTTP service that go-ipfs uses to download the migration binary. Unfortunately go-ipfs does not by default download migrations over IPFS yet, so censoring a few domain can cause problems.

However, as mentioned in the linked issue you still have some options. One is to download and run the latest version of fs-repo-migrations from dist.ipfs.io which can be accessed using your existing version of IPFS.  For example you can try downloading the latest version of fs-repo-migrations by browsing the website at `http://localhost:8080/ipfs/QmYRLRDKobvg1AXTGeK5Xk6ntWTsjGiHbyNKhWfz7koGpa` (your local gateway port might vary, or you might want to use some other gateway), or `http://localhost:8080/ipns/dist.ipfs.io`. Alternatively, you could download the code from this repo and build and run it yourself.

Once you have the  fs-repo-migrations binary you can just run it directly to perform the migration.

**Comment by lidel** [comment]
See https://github.com/ipfs/ipfs-desktop/issues/1773#issuecomment-867095668
