### ISSUE TITLE
“fs-repo-10-to-11” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by oluapocram** [ipfs/fs-repo-migrations#136]
Since upgrading to IPFS Desktop 0.16.1 and go-ipfs 0.9.0 I'm getting the following error message when visiting an IPFS site via Brave (Version 1.27.97 Chromium: 91.0.4472.124 (Official Build) dev (x86_64)). macOS Big Sur (11.4). 

![image](https://user-images.githubusercontent.com/28657119/124964999-83132f00-dfd6-11eb-9be7-8b013a103e38.png)

**Comment by lidel** [comment]
Let's continue in https://github.com/ipfs/go-ipfs/issues/8240 
(Brave is already working on the fix, they will include signed and notarized `fs-repo-10-to-11` in their IPFS component.
