### ISSUE TITLE
Help needed migration 0.8.0 to 0.9.0 with go-ds-s3 

### ISSUE THREAD

**Issue by kevenboo** [ipfs/fs-repo-migrations#138]
We currently have an IPFS server in version 0.8.0 and we would like to migrate it to 0.9.0 in the main time, we would like to add the plugin go-ds-s3 in our version 0.9.0. 
From what I saw in the go-ds-s3 repository the plugin can be added to an IPFS server without data otherwise a datastore migration would have to be performed so we have to implement it in the 0.9.0 and migrate the data from the 0.8.0  to the new one. Unless I am missing something

To to a migration it has to be something like repo 9-to-10 or 10-to-11 but we want 0.9 to 0.9 so it would be 11-to-11 but when I tried the build script I got an error.

`./build-plugin.sh -y 11-to-11 github.com/ipfs/go-ds-s3`

_migration  does not exist_

I am new to IPFS so I don't know if there is something that I am missing or that I got wrong.

Thank you

**Comment by guseggert** [comment]
Repo migrations aren't intended for datastore conversions, take a look at https://github.com/ipfs/ipfs-ds-convert
