### ISSUE TITLE
Migration on Windows doesn't handle default IPFS_PATH

### ISSUE THREAD

**Issue by NightRa** [ipfs/fs-repo-migrations#14]
On windows, if no 'IPFS_PATH' was set, the migration tools complains with "could not determine IPFS_PATH, home dir not set".
The default path is in the user's directory under `.ipfs`
Setting the variable to this folder solved the issue for me.

**Comment by whyrusleeping** [comment]
@NightRa what is an easy way to find a users home directory on windows? (programmatically)

**Comment by NightRa** [comment]
Possibly the %USERPROFILE% env. variable. But better check where exactly ipfs puts it's dir by default

**Comment by jbenet** [comment]
We should have a way of making this a variable in windows

**Comment by hsanjuan** [comment]
Probably fixed in f15601c4
