### ISSUE TITLE
ipfs daemon -c PATH --migrate doesn't use supplied path

### ISSUE THREAD

**Issue by iohzrd** [ipfs/fs-repo-migrations#153]
I use go-ipfs in my project https://github.com/iohzrd/identia.
I try to keep IPFS (along with all my dependencies) up-to-date but, i'm having trouble doing so as there isn't a clear way to migrate from v0.11 to v0.12 without manual intervention...

What I've tried so far:
```
$ ipfs daemon -c /home/user/.config/identia  --migrate
Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: amd64/linux
Golang version: go1.16.12
Found outdated fs-repo, migrations need to be run.
The migrations of fs-repo failed:
  stat /home/user/.ipfs: no such file or directory
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: stat /home/user/.ipfs: no such file or directory
```
Keep in mind that the migration needs to be done programmatically and not but the user. And, my app does not depend on electron or any node runtime, so using the JS ipfs-repo-migrations package is not an option.

**Comment by iohzrd** [comment]
I was able to solve my issue by setting the IPFS_PATH environment variable. That being said, it would still be nice to be able to pass the path directly from ipfs to fs-repo-migrations. I'm gonna leave this issue open for now, until I get a response.

**Comment by guseggert** [comment]
Using IPFS_PATH is the way to switch repos, `-c` is only for switching config, so I don't think there's anything to do here.
