### ISSUE TITLE
Migrating downward to a previous version is not documented

### ISSUE THREAD

**Issue by chriscool** [ipfs/fs-repo-migrations#16]
It is not clear from the doc and from running `fs-repo-migrations -h` if it is possible to go back to a previous version or not. And if it is possible it is not clear how.

**Comment by RichardLitt** [comment]
I've been working on this in https://github.com/ipfs/fs-repo-migrations/pull/10.

**Comment by chriscool** [comment]
@RichardLitt thanks!

**Comment by hsanjuan** [comment]
See linked issue in linked issue
