### ISSUE TITLE
bug: repo migration errors

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/fs-repo-migrations#182]
Many users are reaching out to ipfs-desktop reporting issues with repo migration.. One in particular caught my eye:

From https://github.com/ipfs/ipfs-desktop/issues/2629: 

```bash
Error: Initializing daemon...
Kubo version: 0.22.0
Repo version: 14
System version: amd64/windows
Golang version: go1.19.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 3 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Downloading migration: fs-repo-12-to-13...
Downloading migration: fs-repo-13-to-14...
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-12-to-13/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-12-to-13/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-12-to-13/versions"
```

**If the user is on repo version 14, why is kubo/fs-repo-migrations downloading 11-to-12, 12-to-13, and 13-to-14?**

Other similar repo migration failures:

* https://github.com/ipfs/ipfs-desktop/issues/2554#issuecomment-1638859969
* https://github.com/ipfs/ipfs-desktop/issues/2572

**Comment by SgtPooki** [comment]
**Note**: I realized after posting this that the current repo version isn't output in the logs. This could be converted into a feature request to add output showing the current version of the repo.

may be related to https://github.com/protocol/bifrost-infra/issues/2765

**Comment by SgtPooki** [comment]
it does seem like repo-migration is broken for one particular windows user: `Error: migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations99369112\fs-repo-13-to-14.exe: The parameter is incorrect.`

what parameter, and what's incorrect about it? 

The user seems to run into this issue anytime they try to update ipfs-desktop passed version 0.28.0 (which had kubo v0.20.0). see https://github.com/ipfs/ipfs-desktop/issues/2607

**Comment by Goodebags** [comment]
Yes. That's me with the issue. I'm stuck on v 0.28.0 and if I try to update to a more recent version, I get the error message as above.  
I had wondered if it might be feasible to save/bckup the data on my local node, uninstall and reinstall latest IPFS and then re-attach the data... if such a thing is possible?
Any help gratefully received and thank you SgtPooki

**Comment by Goodebags** [comment]
This is the error message that I get whenever I try to update:
Initializing daemon...
Kubo version: 0.22.0
Repo version: 14
System version: amd64/windows
Golang version: go1.19.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-13-to-14...
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/v1.0.0/fs-repo-13-to-14_v1.0.0_windows-amd64.zip"
Downloaded and unpacked migration: C:\Users\User\AppData\Local\Temp\migrations3454220631\fs-repo-13-to-14.exe (v1.0.0)
Running migration fs-repo-13-to-14 ...
  => Running: C:\Users\User\AppData\Local\Temp\migrations3454220631\fs-repo-13-to-14.exe -path=G:\IPFS\.ipfs -verbose=true
The migrations of fs-repo failed:
  migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3454220631\fs-repo-13-to-14.exe: The parameter is incorrect.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3454220631\fs-repo-13-to-14.exe: The parameter is incorrect.

**Comment by Goodebags** [comment]
Still stuck. 
I followed the suggestion:

[With IPFS-Desktop](https://github.com/ipfs/ipfs-desktop#with-ipfs-desktop)
Go to the Settings tab
Find "Migrations" in the config, and update the DownloadSources array to be ["IPFS", "https://dweb.link", "https://cloudflare-ipfs.com", "HTTP"]

Then i updated again to the latest version 0.31.0 and this is the error message that I get:

Initializing daemon...
Kubo version: 0.23.0
Repo version: 15
System version: amd64/windows
Golang version: go1.21.1
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 2 migrations, downloading.
Downloading migration: fs-repo-13-to-14...
Downloading migration: fs-repo-14-to-15...
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:54 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Fetching with IPFS: "fs-repo-14-to-15/versions"
Fetching with IPFS: "fs-repo-13-to-14/versions"
2023/10/15 10:45:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:58 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:58 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:58 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:58 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:45:58 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Fetching with IPFS: "fs-repo-13-to-14/v1.0.0/fs-repo-13-to-14_v1.0.0_windows-amd64.zip"
2023/10/15 10:46:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Downloaded and unpacked migration: C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-13-to-14.exe (v1.0.0)
2023/10/15 10:46:24 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:24 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:24 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:24 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:24 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Error fetching: error traversing node at "fs-repo-14-to-15": could not load link "QmQ4HRShns9YPE1FAtfjZzNWmgBQcgWEEkkocHR9d7q96h": context deadline exceeded
Fetching with HTTP: "https://dweb.link/ipfs/QmZPedUiZNe6Gq9oDvoizuuCMVoeb7shwq9xKhysq7exMo/fs-repo-14-to-15/versions"
2023/10/15 10:46:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:46:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Fetching with IPFS: "fs-repo-14-to-15/v1.0.1/fs-repo-14-to-15_v1.0.1_windows-amd64.zip"
2023/10/15 10:47:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:47:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:47:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:47:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/10/15 10:47:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Error fetching: error traversing node at "fs-repo-14-to-15": could not load link "QmQ4HRShns9YPE1FAtfjZzNWmgBQcgWEEkkocHR9d7q96h": context deadline exceeded
Fetching with HTTP: "https://dweb.link/ipfs/QmZPedUiZNe6Gq9oDvoizuuCMVoeb7shwq9xKhysq7exMo/fs-repo-14-to-15/v1.0.1/fs-repo-14-to-15_v1.0.1_windows-amd64.zip"
Downloaded and unpacked migration: C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-14-to-15.exe (v1.0.1)
Running migration fs-repo-13-to-14 ...
  => Running: C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-13-to-14.exe -path=G:\IPFS\.ipfs -verbose=true
The migrations of fs-repo failed:
  migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-13-to-14.exe: The parameter is incorrect.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-13-to-14.exe: The parameter is incorrect.

**Comment by aschmahmann** [comment]
@Goodebags if you manually rerun the failed command `C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-13-to-14.exe -path=G:\IPFS.ipfs -verbose=true` does it fail with the same error or succeed? If the temp file is no longer there if you can download and run the exe from https://dist.ipfs.tech/fs-repo-13-to-14/v1.0.0/.

**Comment by Goodebags** [comment]
...and if I run that command now, I get:

C:\>C:\Users\User\AppData\Local\Temp\migrations3296180791\fs-repo-13-to-14.exe -path=G:\IPFS.ipfs -verbose=true
applying 13-to-14 repo migration
locking repo at "G:\\IPFS.ipfs"
error: failed to acquire repo lock at G:\IPFS.ipfs/repo.lock
Is a daemon running? please stop it before running migration

**Comment by lidel** [comment]
@Goodebags for the record, quick questions:
- is `G:` a local disk in you PC, or a network drive?
- is your Windows box up-to-date?
- are you running any antivirus / firewall software?

**Comment by Goodebags** [comment]
Hi Lidel and thanks for replying
G: is a large external hard drive that lives attached to my PC (it doesn't have a very large hard drive built in).
Windows is up to date
I run Comodo Internet security and run a trust zone VPN.

**Comment by lidel** [comment]
Triage notes:
- difficult to tell given both VPN and Comodo AV software are running
  - @Goodebags are you able to shut them down and retry? `ipfs.io` is likely blocked by your AV.
- Otherwise, this may go away once we switch migrations to  trustless CAR retrieval (https://github.com/ipfs/kubo/issues/9159) so users have fallback for cases where ipfs.io is blocked by AV/ISP

**Comment by Goodebags** [comment]
Wow! Awesome. Well done!
I went into comodo and unblocked all of the tasks related to IPFS and migrations, etc and updated again to v 0.31.0 and after a very long (what looked like was going to be a fail), it worked and v 0.23.0 is now working on my PC 

Initializing daemon...
Kubo version: 0.23.0
Repo version: 15
System version: amd64/windows
Golang version: go1.21.1
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-14-to-15...
2023/11/22 09:56:45 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:45 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:45 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:45 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:45 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:46 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:46 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:46 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Fetching with IPFS: "fs-repo-14-to-15/versions"
2023/11/22 09:56:46 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:47 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Fetching with IPFS: "fs-repo-14-to-15/v1.0.1/fs-repo-14-to-15_v1.0.1_windows-amd64.zip"
2023/11/22 09:56:49 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:49 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:49 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:49 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:49 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:56:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Downloaded and unpacked migration: C:\Users\User\AppData\Local\Temp\migrations2152272985\fs-repo-14-to-15.exe (v1.0.1)
Running migration fs-repo-14-to-15 ...
  => Running: C:\Users\User\AppData\Local\Temp\migrations2152272985\fs-repo-14-to-15.exe -path=G:\IPFS\.ipfs -verbose=true
applying 14-to-15 repo migration
locking repo at "G:\\IPFS\\.ipfs"
  - verifying version is '14'
> Upgrading config to new format
updated version file
Migration 14 to 15 succeeded
Success: fs-repo migrated to version 15.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:07 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:08 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:08 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:08 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Swarm listening on /ip4/10.0.0.129/tcp/4001
Swarm listening on /ip4/10.0.0.129/udp/4001/quic-v1
Swarm listening on /ip4/10.0.0.129/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm listening on /ip4/169.254.114.217/tcp/4001
Swarm listening on /ip4/169.254.114.217/udp/4001/quic-v1
Swarm listening on /ip4/169.254.114.217/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm listening on /ip4/169.254.28.204/tcp/4001
Swarm listening on /ip4/169.254.28.204/udp/4001/quic-v1
Swarm listening on /ip4/169.254.28.204/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm listening on /ip4/192.168.0.15/tcp/4001
Swarm listening on /ip4/192.168.0.15/udp/4001/quic-v1
Swarm listening on /ip4/192.168.0.15/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic-v1
Swarm listening on /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.0.0.129/tcp/4001
Swarm announcing /ip4/10.0.0.129/udp/4001/quic-v1
Swarm announcing /ip4/10.0.0.129/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm announcing /ip4/89.238.183.202/udp/4001/quic-v1
Swarm announcing /ip4/89.238.183.202/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic-v1
Swarm announcing /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiDkMDeIzFHRiMIiuBVOqf10AYZ4X-tetojLTGEM4AeM2w/certhash/uEiC0q3XT8mK42a9dzG3oO84oRFpt0gi-E6YpgY5mScbRbg
RPC API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
connected to migration peer "{12D3KooWSKR56HXQgLPry6ig1RsmwMmxAtV43pi91VDFyTPxjmqE: [/ip4/127.0.0.1/tcp/64078]}"
Added migration file: "/ipfs/QmZPedUiZNe6Gq9oDvoizuuCMVoeb7shwq9xKhysq7exMo/fs-repo-14-to-15/versions"
2023/11/22 09:57:09 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Added migration file: "/ipfs/QmZPedUiZNe6Gq9oDvoizuuCMVoeb7shwq9xKhysq7exMo/fs-repo-14-to-15/v1.0.1/fs-repo-14-to-15_v1.0.1_windows-amd64.zip"
Added migration file "fs-repo-14-to-15_v1.0.1_windows-amd64.zip": /ipfs/QmcpfEejFxfp1CXEqRJnHKUBFFxdRH2VrXtwZc5NZFpyyp
Added migration file "fs-repo-14-to-15_v1.0.1_windows-amd64.zip": /ipfs/QmcpfEejFxfp1CXEqRJnHKUBFFxdRH2VrXtwZc5NZFpyyp
Added migration file "fs-repo-14-to-15_v1.0.1_windows-amd64.zip": /ipfs/QmcpfEejFxfp1CXEqRJnHKUBFFxdRH2VrXtwZc5NZFpyyp
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:10 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/11/22 09:57:11 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
Gateway server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

So I guess, all good now!?
Thank you very much and best wishes
Rich
