### ISSUE TITLE
make the 2-3-pins test check if objects are there too

### ISSUE THREAD

**Issue by jbenet** [ipfs/fs-repo-migrations#21]
the 2-3pins test checks the pins but does not:
- check the objects are there
- run gc 
between every change of version

it also does not remove pins objects. 

an important goal of these tests is to exercise the pinset across versions, including deletion of pins and GCs that do remove some content and leave other content.

**Comment by jbenet** [comment]
this migration is really critical to get right. these tests should build on this: https://github.com/ipfs/go-ipfs/issues/2343

As things are now, I'm far from certain this migration will proceed without any hitch for users. ipfs MUST NEVER lose any data, and i'm not confident in the tests yet (either for go-ipfs@0.4.0 nor fs-repo-migrations 2-3). this is going to be the first major data migration for users and we need to be at the top of our certainty.

**Comment by whyrusleeping** [comment]
Hey @chriscool could you add these checks to the sharness tests here?

**Comment by chriscool** [comment]
Yeah, I will take a look at adding something like that.
I wanted to add tests using the daemon first, then I looked at iptb to launch the daemon, then it appeared that iptb was not using gx yet...

**Comment by whyrusleeping** [comment]
@chriscool in the meantime we can use go get to pull down iptb (`go get github.com/whyrusleeping/iptb`) it has very few external dependencies.

**Comment by chriscool** [comment]
Yeah I will have another look at using iptb.

**Comment by chriscool** [comment]
So we don't use iptb but we do check the objects are there and run gc between every change of version.
