### ISSUE TITLE
'ipfs-update versions' cannot resolve name

### ISSUE THREAD

**Issue by chriscool** [ipfs/fs-repo-migrations#24]
I am getting this error now:

```
> bin/ipfs-update versions
ERROR: fetching resource: 400 Bad Request
ERROR: Failed to query versions:  400 Bad Request: Path Resolve error: could not resolve name.
```

Any idea about what's going on?

**Comment by whyrusleeping** [comment]
we're going to need to update the version of ipfs-update thats vendored in here. I think that the `update.ipfs.io` domain got removed, the newer code uses `dist.ipfs.io`

**Comment by lgierth** [comment]
Ugh yep I removed it just the other day.

**Comment by lgierth** [comment]
Can add it back in for a while if that makes sense

**Comment by whyrusleeping** [comment]
nah, its fine. we should just update the version of ipfs-update

**Comment by chriscool** [comment]
Ok I will take a look at that.

**Comment by chriscool** [comment]
This is fixed now.
