### ISSUE TITLE
Migrating a specific ipfs instance

### ISSUE THREAD

**Issue by elenadimitrova** [ipfs/fs-repo-migrations#37]
Currently not able to upgrade an ~/.ipfs2 instance via fs-repo-migrations as this does not accept location argument for the target to upgrade.

**Comment by chriscool** [comment]
Maybe a work around could be to rename the instance temporarily for the time of the upgrade.

**Comment by elenadimitrova** [comment]
I already have another (default) instance so that's not an option. Plus I have already found a workaround. I listed this as an issue because it needs to be solved in the tool.

**Comment by lgierth** [comment]
Try this setting `IPFS_PATH=~/.ipfs2` with the command

**Comment by hsanjuan** [comment]
> Try this setting `IPFS_PATH=~/.ipfs2` with the command

That should work.
