### ISSUE TITLE
Migration 3 to 4 failed

### ISSUE THREAD

**Issue by chevdor** [ipfs/fs-repo-migrations#46]
```
$ fs-repo-migrations
Found fs-repo version 3 at /Users/will/.ipfs
Do you want to upgrade this to version 4? [y/n] y
===> Running migration 3 to 4...
applying 3-to-4 repo migration
locking repo at "/Users/will/.ipfs"
  - verifying version is '3'
  - opening datastore at "/Users/will/.ipfs"
transfering blocks to new key format
enumerating keysskipping (no .data):  12204961/put-676068147
skipping (no .data):  12205497/put-106496515
skipping (no .data):  1220553f/put-763233442
skipping (no .data):  122063bf/put-044131062
enumerating keys...skipping (no .data):  1220c4f1/put-380945039
enumerating keys....skipping (no .data):  1220f279/put-415760420
skipping (no .data):  1220f2c9/put-732064153
[1 / 11872]failed to decode: /Users/will/.ipfs/blocks/CIQA2/CIQA23O4Q<....>7N2PPGBKBZFBUDYZA.data
ipfs migration:  migration 3 to 4 failed: encoding/hex: odd length hex string
```

**Comment by whyrusleeping** [comment]
@chevdor did you modify the output at all? I'm interested in the full string of `CIQA23O4Q<....>7N2PPGBKBZFBUDYZA.data`. It somehow fails to parse as a valid 'new style' (base32) key.

**Comment by chevdor** [comment]
I did yes.
Is it 'safe' to disclose this string entirely?

**Comment by whyrusleeping** [comment]
It does identify content that you have in your ipfs node, so its safe if you don't mind associating yourself with that content. but don't worry about it. I just found the problem anyways :)

**Comment by whyrusleeping** [comment]
Alright, if you feel like building from source. You can pull latest master of this repo and try it out. Otherwise i will be pushing a new release of this out fairly soon (hopefully this week).

**Comment by lgierth** [comment]
That's 1e510aa6a48b7f3d6558c9116e86053b44985a2c, for the record

**Comment by chevdor** [comment]
Woo awesome. I will not build right now but I will check tomorrow. That was
fast!

**Comment by whyrusleeping** [comment]
@chevdor pre-built binaries are up here: https://ipfs.io/ipfs/QmU8gYRCdbRc69B9h1yanB5LNHCc9vfsAmk8bZdMRXAJsw/

Theyre rolling out to the dists page soon, and will be pushed into the go-ipfs binaries auto-migrater sometime this week.

**Comment by chevdor** [comment]
I had issues building but I tested your binary and I confirm (and thus close this issue) that you fixed the issue. Thanks a lot.
