### ISSUE TITLE
Recovery Notes

### ISSUE THREAD

**Issue by kevina** [ipfs/fs-repo-migrations#50]
Notes on recovery when the automatic migration fails:

https://gist.github.com/kevina/d39e800ddffed217ca149c600f0735e4

**Comment by kevina** [comment]
@whyrusleeping not sure what to do with these so I just put in a gist...

**Comment by hsanjuan** [comment]
Closing, I don't see actionables that will be worked on and hopefully no one needs to run those migrations at this point.
