### ISSUE TITLE
failed to convert flatfs datastore (4 -> 5)

### ISSUE THREAD

**Issue by vitlav** [ipfs/fs-repo-migrations#52]
During migration to go-ipfs 0.4.5
```
Found fs-repo version 4 at /home/ipfs/.ipfs
===> Running migration 4 to 5...
applying 4-to-5 repo migration
locking repo at "/home/ipfs/.ipfs"
  - verifying version is '4'
> Upgrading datastore format to have sharding specification file
> creating a new flatfs datastore with new format
> converting current flatfs datastore to new format
Moving Keys...
7230 keys so farfailed to decode entry in flatfs
20940 keys so farfailed to decode entry in flatfs
31630 keys so farfailed to decode entry in flatfs
...
```
I got
ERROR: failed to convert flatfs datastore: remove /home/ipfs/.ipfs/blocks-v4/CIQN3: directory not empty
attempting to revert...

And I wondering about 'failed to decode entry in flatfs' lines during moving.

Details:
https://gist.github.com/vitlav/090c09353be611238574df0115ce9115

**Comment by vitlav** [comment]
There are a few files put-* in blocks subdirs:
$ find /home/ipfs/.ipfs/blocks | grep -v "\.data$" | grep put
/home/ipfs/.ipfs/blocks/CIQN3/put-473695657
/home/ipfs/.ipfs/blocks/CIQGG/put-230303092
/home/ipfs/.ipfs/blocks/CIQC3/put-622440535
/home/ipfs/.ipfs/blocks/CIQJ5/put-226512362
/home/ipfs/.ipfs/blocks/CIQAS/put-758247077
/home/ipfs/.ipfs/blocks/CIQEP/put-812939647

Need I just remove all of them?

**Comment by Kubuxu** [comment]
Yes, you can remove them. Fix for it will be released with 0.4.6

**Comment by jbenet** [comment]
why is fixing the `4-5` migration blocked on `go-ipfs@0.4.6`? shouldnt the fix be in the 4-5 migration only? why cant that be fixed + released now?

**Comment by Kubuxu** [comment]
Migrations itself can be, auto-migrations with daemon is planned for 0.4.6

**Comment by jbenet** [comment]
why is the auto-migration not possible until 0.4.6? isn't it just a matter of releasing a new version of the binary and updating dist.ipfs.io?

**Comment by whyrusleeping** [comment]
@jbenet Yeah, its not blocked on 0.4.6, we will be pushing a new version of migrations out today.

**Comment by whyrusleeping** [comment]
@vitlav Those are temporary files left over from botched atomic write operations. They are completely safe to remove.

**Comment by jbenet** [comment]
thanks @whyrusleeping
