### ISSUE TITLE
Migration backward failure

### ISSUE THREAD

**Issue by jbenet** [ipfs/fs-repo-migrations#54]
```
> ipfs version
ipfs version 0.4.5
> ipfs-update install v0.4.4
fetching go-ipfs version v0.4.4
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /Users/jbenet/go/bin/ipfs
checking if repo migration is needed...
  - Migration required
fetching fs-repo-migrations version v1.2.0
running migration: '/var/folders/27/vc54xwmx2q5dvx9y9vcss5l00000gn/T/ipfs-update-migrate541727985/fs-repo-migrations -to 4 -y'
ipfs migration: already at or above target version number
migration succeeded!

installation complete.
> ipfs version
ipfs version 0.4.4
> ipfs daemon
Initializing daemon...
Error: Your programs version (4) is lower than your repos (5).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
```

Obviously this is wrong.

- fs-repo-migrations failed to migrate back. there is an error when checking versions. it assumes `fs-repo-migrations -to 4 -y` is only forward. and therefore ipfs-update's (normal behavior) failed.
- I think this requires fixing fs-repo-migrations.

**Comment by jbenet** [comment]
cc @whyrusleeping @Kubuxu

**Comment by jbenet** [comment]
This is naive: https://github.com/ipfs/fs-repo-migrations/blob/master/main.go#L157 -- it needs to be updated to allow for forward and backward migrations. 

Naturally, running it manually does not work either:

```
> /var/folders/27/vc54xwmx2q5dvx9y9vcss5l00000gn/T/ipfs-update-migrate541727985/fs-repo-migrations -to 4 -y
ipfs migration: already at or above target version number
```

- We've previously discussed that go-ipfs MAY only auto-migrate up. This is a separate discussion. this discussion is about (ostensibly) a manual migration using `fs-repo-migrations` down.

**Comment by whyrusleeping** [comment]
@jbenet You can manually revert with the individual sub-tools (i.e. `ipfs-4-to-5`). We had previously discussed this as being okay, but i'm also fine allowing this tool to do it as well. Perhaps with an explicit `--i-know-this-is-a-revert` flag?

**Comment by jbenet** [comment]
i like explicitness. i've a PR up. needs that additional flag. maybe `--revert-ok`  ? 

- `ipfs-update` is really annoying to downgrade without this.

**Comment by jbenet** [comment]
Also, the individual subtools are not pre-compiled (to my knowledge) so the barrier for the user gets super high super fast.

Take a look at #55

**Comment by whyrusleeping** [comment]
@jbenet Yeah, agreed. It should be easier

**Comment by hsanjuan** [comment]
I'm closing as original issue is fixed, and there's an issue about documenting downgrades.

**Comment by SgtPooki** [comment]
@hsanjuan can you link to the issue about downgrades? I just got the message that my repo version is ahead of my ipfs-desktop version and the error message told me to run the migration in reverse and linked me to https://github.com/ipfs/fs-repo-migrations/blob/master/run.md which doesn't have instructions about running migrations in reverse.

ideally, this scenario would only occur for devs running the latest kubo release to test things, but there are valid use-cases for non-devs who downgrade to avoid bugs.

**Comment by hsanjuan** [comment]
> @hsanjuan can you link to the issue about downgrades?

Sure: https://github.com/ipfs/ipfs-docs/issues/278
