### ISSUE TITLE
4 to 5 migration failure : rename failed no such file or directory

### ISSUE THREAD

**Issue by eminence** [ipfs/fs-repo-migrations#60]
Currently running:

```
go-ipfs version: 0.4.8-rc1-
Repo version: 5
System version: amd64/linux
Golang version: go1.7.1
```

Commit a8b56d3ad7789ca2ec12257a00d8d0408c3c0c9e

```
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] Y
  => Looking for suitable fs-repo-migrations binary.
  => Running: /storage/home/achin/devel/gopath/bin/fs-repo-migrations -to 5 -y
Found fs-repo version 4 at /nas/achin/ipfs
===> Running migration 4 to 5...
applying 4-to-5 repo migration
locking repo at "/nas/achin/ipfs"
  - verifying version is '4'
> Upgrading datastore format to have sharding specification file
> creating a new flatfs datastore with new format
> converting current flatfs datastore to new format
Moving Keys...
22790 keys so farERROR: failed to convert flatfs datastore: rename /nas/achin/ipfs/blocks-v4/12205/1220543aa6f6b9a533c8bf80568090cdf24b693aaa2f9b574a33784d8462fdc5579c.data /nas/achin/ipfs/blocks-v5/79/1220543aa6f6b9a533c8bf80568090cdf24b693aaa2f9b574a33784d8462fdc5579c.data: no such file or directory
attempting to revert...
Moving Keys...
22790 keys so far
Cleaning Up...
All Done.
ipfs migration:  migration 4 to 5 failed: rename /nas/achin/ipfs/blocks-v4/12205/1220543aa6f6b9a533c8bf80568090cdf24b693aaa2f9b574a33784d8462fdc5579c.data /nas/achin/ipfs/blocks-v5/79/1220543aa6f6b9a533c8bf80568090cdf24b693aaa2f9b574a33784d8462fdc5579c.data: no such file or directory
  => Failed: /storage/home/achin/devel/gopath/bin/fs-repo-migrations -to 5 -y
The migrations of fs-repo failed:
  migration failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
Error: migration failed: exit status 1

```

**Comment by whyrusleeping** [comment]
Hrm... I thought we resolved this.

cc @Kubuxu @kevina

**Comment by kevina** [comment]
Of hand I am not sure what is going on.  The only thing I can think of is that an IPFS (or some other process) was modifying the datastore at the same time, but I would think the lock would avoid that.

**Comment by eminence** [comment]
there are no other IPFS processes running

**Comment by kevina** [comment]
okay we worked it out over irc:  it looks like the problem was some files left over from an old migration (or something) in the blocks directory that where confusing the migration tool:
```
11147119/11147119ce39ee9a3ebc02fdc81eb265c04da90ea5db.data
1220543a/1220543aa6f6b9a533c8bf80568090cdf24b693aaa2f9b574a33784d8462fdc5579c.data
```

**Comment by eminence** [comment]
I confirm that after removing these two file, the migration was successful, and my daemon is running once again.  Many thanks to @kevina

**Comment by whyrusleeping** [comment]
@kevina how do we want to handle this better? We should probably detect this scenario and notify the user

**Comment by kevina** [comment]
The best thing to do would be to provide a better error message.  When a file is not found, determine if the reason is because a block is not stored in the correct location based on the shard function and give a clear indication of the fact and suggest the user moves the file out of the datastore directory.

I am guessing that this files exist based from some old test code and this is not a situation most users will encounter.

**Comment by whyrusleeping** [comment]
@kevina cool, could you PR in that change?

**Comment by kevina** [comment]
I will p.r. go-ds-flatfs since that is where the change needs to be.

**Comment by Centaro0** [comment]
> okay we worked it out over irc: it looks like the problem was some files left over from an old migration (or something) in the blocks directory that where confusing the migration tool:
> 
> ```
> 11147119/11147119ce39ee9a3ebc02fdc81eb265c04da90ea5db.data
> 1220543a/1220543aa6f6b9a533c8bf80568090cdf24b693aaa2f9b574a33784d8462fdc5579c.data
> ```

Where were the files located? I am having the same problem in 2020, but mlocate cannot find these files in my machine.

**Comment by gammazero** [comment]
Have not seen other reports of this issue.  No further need to support 4 to 5 migration issues.
