### ISSUE TITLE
Data folder trying to be renamed to the same name on Windows

### ISSUE THREAD

**Issue by caellach** [ipfs/fs-repo-migrations#65]
While testing some changes to ipfs-update, this was output from fs-repo-migrations. 
(Note: I bypassed the checks in ipfs-update to test fs-repo-migrations execution on Windows, but I don't have old data to migrate so I'm not sure yet why it's starting w/ v1 in that case since I should only have the latest IPFS data version)

    fetching go-ipfs version v0.4.10
    binary downloaded, verifying...
    success! tests all passed.
    installing new binary to C:\Go\bin\ipfs.exe
    checking if repo migration is needed...
      check complete, migration required.
    fetching fs-repo-migrations version v1.2.2
    running migration: 'C:\Users\<USER>\AppData\Local\Temp\ipfs-update-migrate040886245\fs-repo-migrations.exe -to 5 -y'
    Found fs-repo version 1 at C:\Users\<USER>/.ipfs
    ===> Running migration 1 to 2...
    performed sanity check
    
    moved blocks from leveldb to flatfs
    ipfs migration:  migration 1 to 2 failed: rename C:\Users\<USER>/.ipfs C:\Users\<USER>/.ipfs: Access is denied.
    ERROR: Migration Failed:  migration failed: exit status 1
    install failed, reverting changes...
    ERROR: migration failed: exit status 1

**Comment by hsanjuan** [comment]
Likely an issue of trying to migrate something that does not need migration. I'm closing for the moment.
