### ISSUE TITLE
Add /dnsaddr bootstrap addresses in 5-to-6 migration

### ISSUE THREAD

**Issue by ghost** [ipfs/fs-repo-migrations#67]
Hey @kevina, I mentioned on IRC that there's another config change I'd like to get into the 5-to-6 migration. Sorry I'm bringing this forward at the 11th hour. At least it only simply adds list values, and doesn't do any structural changes.

What I have in mind is adding `/dnsaddr` addresses for each of the default QmSoL bootstrappers. The current addresses are very fragile since they are coupled with the DigitalOcean hosts that currently run the bootstrappers. This actually makes the IPFS network quite vulnerable since anyone can just attack these 8 little hosts. The `/dnsaddr` on the other hand works similarly to dnslinks -- check out the examples in https://github.com/multiformats/go-multiaddr-dns.

I'm fine doing this in another PR on top of yours, but it would be great if you could look into it since you already have all the context present. Otherwise I can give it a try next week.

Migration:
- for each default `Bootstrap` item
  - if item's PeerID starts with `QmSoL`
  - and if `Bootstrap` actually contains the item
    - append `/dnsaddr/bootstrap.libp2p.io` for this item to `Bootstrap` list
    - e.g. for `/ip4/1.2.3.4/tcp/4001/ipfs/QmSoL`, append `/dnsaddr/bootstrap.libp2p.io/ipfs/QmSoL`

Revert:
- for each item in `Bootstrap`
  - if item starts with `/dns`
    - remove the item from `Bootstrap`

**Comment by kevina** [comment]
@lgierth I am not familiar with the networking code in IPFS so I am not that comfortable doing this, but if push comes to shove I like I can do it

However, I am also lacking context, is this something that was discussed with @whyrusleeping or others?  Is this something that is generally wanted?

**Comment by gammazero** [comment]
No longer updating the 5-to-6 migration.  Closing.
