### ISSUE TITLE
fs-repo-migrations upgrades to an unsupported version

### ISSUE THREAD

**Issue by NfNitLoop** [ipfs/fs-repo-migrations#70]
Scenario
---------

 * I haven't used ipfs in ages.   
 * `ipfs` tells me I need to run a migration. 
 * I download and run fs-repo-migrations
 * It upgrades me to repo version 6

Issue
-----

 I'm running the the latest version of `ipfs` from Homebrew, which only supports repo version 5:

~~~
> ipfs version --all
go-ipfs version: 0.4.10-4679f80
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3
~~~

And `fs-repo-migrations -to 5` doesn't work.   I got some suggestions for how to downgrade manually in #ipfs but it sounds like a pain.  It would be nice if it had just upgraded to 5, since that's what my `ipfs` claims to support. Seems like an easy enough check?

**Comment by jbshirk** [comment]
I have a similar issue:
haven't used ipfs in ages. run the migration tool (today). install the latest ipfs. start daemon:

MacBook-Pro-4:Downloads joe$ fs-repo-migrations/fs-repo-migrations 
Found fs-repo version 4 at /Users/joe/.ipfs
Do you want to upgrade this to version 6? [y/n] y
===> Running migration 4 to 5...
applying 4-to-5 repo migration
locking repo at "/Users/joe/.ipfs"
  - verifying version is '4'
> Upgrading datastore format to have sharding specification file
> creating a new flatfs datastore with new format
> converting current flatfs datastore to new format
Moving Keys...
600 keys so far
Cleaning Up...
2017/09/22 21:25:27 found unexpected file in datastore directory: ".DS_Store", moving anyway
All Done.
> moving new datastore into place
> moving transferred datastore back into place
updated version file
===> Migration 4 to 5 succeeded!
===> Running migration 5 to 6...
applying 5-to-6 repo migration
locking repo at "/Users/joe/.ipfs"
  - verifying version is '5'
> Upgrading config to new format
updated version file
===> Migration 5 to 6 succeeded!
MacBook-Pro-4:Downloads joe$ cd ..
MacBook-Pro-4:~ joe$ pwd
/Users/joe
MacBook-Pro-4:~ joe$ cd Downloads/
MacBook-Pro-4:Downloads joe$ cd go-ipfs
MacBook-Pro-4:go-ipfs joe$ ls
LICENSE		README.md	build-log	install.sh	ipfs
MacBook-Pro-4:go-ipfs joe$ ./install.sh
Moved ipfs to /usr/local/bin
MacBook-Pro-4:go-ipfs joe$ ipfs daemon
Initializing daemon...
Adjusting current ulimit to 1024.
Error: Your programs version (4) is lower than your repos (6).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.

**Comment by jbshirk** [comment]
my IPFS is dead :(

**Comment by Kubuxu** [comment]
go-ipfs 0.4.11 which uses version 6 was released about two weeks ago.

**Comment by Kubuxu** [comment]
Check you go-ipfs version `ipfs version --all`.

**Comment by jbshirk** [comment]
$ ipfs version --all
go-ipfs version: 0.4.3-dev-33510a9
Repo version: 4
System version: amd64/darwin
Golang version: go1.6.3

**Comment by Kubuxu** [comment]
ipfs 0.4.3 is ancient. Please upgrade to 0.4.11 from https://dist.ipfs.io/#go-ipfs

**Comment by jbshirk** [comment]
Obviously what I am trying to do is upgrade. It isn't working. Are you saying 4.11 properly convert my 4.3 files? Or am I just going to lose my ID and files?

**Comment by Kubuxu** [comment]
Just run use the most recent go-ipfs version. It will work.
