### ISSUE TITLE
The '386' migration binaries contain SSE2 instructions

### ISSUE THREAD

**Issue by fstirlitz** [ipfs/fs-repo-migrations#71]
Although they are advertised as '386', the migration binaries for the, um, x86-32 architecture contain SSE2 instructions, which generate an 'illegal opcode' exception on CPUs older than Pentium 4 (i786). (And possibly some instructions that will crash even that; I haven't checked.) This may leave users unable to actually use the IPFS software after upgrading:

```
$ ipfs daemon
Initializing daemon...
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
The migrations of fs-repo failed:
  no fs-repo-migration binary found for version 6: failed to check migrations version: signal: illegal instruction (core dumped)
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
Error: no fs-repo-migration binary found for version 6: failed to check migrations version: signal: illegal instruction (core dumped)
```

Compiling for an older subarchitecture will of course result in some performance degradation, but given that migrations are supposed to happen rarely (they are, right?), I believe sacrificing performance for portability is acceptable. Newer x86 computers are 64-bit anyway.

As for which x86-32 sub-architecture to target instead... I guess either literal i386 (for maximum portability), or i686, which is targeted by many Linux distributions.

**Comment by hsanjuan** [comment]
I am not sure what would cause the migrations to use SSE2 instructions and not go-ipfs itself to use them. We use `linux 386` to build both.

I am going to close this as this is old, but I'd encourage you to test and re-open if things happen.
