### ISSUE TITLE
6-to-7 migration does not lock repo or check version

### ISSUE THREAD

**Issue by kevina** [ipfs/fs-repo-migrations#73]
In `func (m Migration) Apply(opts migrate.Options) error` I was expecting to see lines similar to:
```
	log.VLog("locking repo at %q", opts.Path)
	lk, err := lock.Lock2(opts.Path)
	if err != nil {
		return err
	}
	defer lk.Close()

	repo := mfsr.RepoPath(opts.Path)

	log.VLog("  - verifying version is '5'")
	if err := repo.CheckVersion("6"); err != nil {
		return err
	}
```
I am not sure if the Lock is necessary here, and I suppose the version check is not required because the repo is opened with `go-ipfs` code.  However, if there is a repo mismatch, it will create a confusing error as to run the migration, from within the migration code itself!

I am opening this issue mainly for how to handle a similar situation in my migration which will clean the repo of insure and identity hashes.

CC @Stebalien

**Comment by Stebalien** [comment]
> I am not sure if the Lock is necessary here, and I suppose the version check is not required because the repo is opened with go-ipfs code.

Correct.

> However, if there is a repo mismatch, it will create a confusing error as to run the migration, from within the migration code itself!

Well, a message to run a different migration, however, yes, it really should state which one. For example:

"repo migration needed: repo has version X, expected repo with version Y"

IMO, we should put this error in go-ipfs itself.

**Comment by gammazero** [comment]
This issue is handled by #116

**Comment by gammazero** [comment]
PR #116 merged. Closing issue.
