### ISSUE TITLE
ipfs migration failed on windows

### ISSUE THREAD

**Issue by Sam3281** [ipfs/fs-repo-migrations#87]
I want to run go-ipfs version: 0.4.20-rc1-5880b3075-dirty, but it mention i should migration to Repo version: 7 .

And then an error occur:

ipfs migration: migration 1 to 2 failed: rename E:\go_work\ipfs E:\go_work\ipfs: Access is denied.

Here is the details of the log:
![image](https://user-images.githubusercontent.com/49011306/56010207-53045500-5d15-11e9-9dfc-ff74098dcb92.png)

I don't know this is a bug or not, please help me to make clear to it.
Thanks .

**Comment by djdv** [comment]
>I don't know this is a bug or not, please help me to make clear to it.

It certainly seems like one.
I tried to initialize a repo, and revert the migrations and received similar errors at the same migration bridges (and more).

```
>SET IPFS_PATH=T:\ipfs
>ipfs init
...
>fs-repo-migrations -to 1 --revert-ok
Found fs-repo version 7 at T:\ipfs
Do you want to upgrade this to version 1? [y/n] y
===> Running migration 7 to 6...
reverting migration
decoding private key
migrating IPNS record for key: self
updated version file
===> Migration 7 to 6 succeeded!
===> Running migration 6 to 5...
reverting migration
ver6to5 done!
lowered version number to 5
===> Migration 6 to 5 succeeded!
===> Running migration 5 to 4...
reverting migration
Moving Keys...
40 keys so far
Cleaning Up...
2019/04/11 23:38:20 found unexpected file in datastore directory: "diskUsage.cache", moving anyway
All Done.
lowered version number to 4
===> Migration 5 to 4 succeeded!
===> Running migration 4 to 3...
reverting migration
  - opening datastore at "T:\\ipfs"
reverting blocks to old key format
gathering keys...
2019/04/11 23:38:20 failed to decode entry in flatfs
got 45 keys, beginning transfer. This will take some time.
[45 / 45]  Approx time remaining: 30s
reverting stored public key records
gathering keys...
got 0 keys, beginning transfer. This will take some time.

reverting stored ipns records
gathering keys...
got 1 keys, beginning transfer. This will take some time.
[1 / 1]
lowered version number to 3
===> Migration 4 to 3 succeeded!
===> Running migration 3 to 2...
reverting migration
  - reverting pins
  - opening datastore at "T:\\ipfs"
ipfs migration:  migration 3 to 2 failed: The process cannot access the file because it is being used by another process.

>fs-repo-migrations -to 1 --revert-ok
Found fs-repo version 3 at T:\ipfs
Do you want to upgrade this to version 1? [y/n] y
===> Running migration 3 to 2...
reverting migration
  - reverting pins
  - opening datastore at "T:\\ipfs"
  - construct dagservice
  - load pinner
  - write old recursive keys
writing keys: "/local/pins/recursive/keys" [QmRQu8GLxb9PThPWReCxiBJ6e25tT9VzG3tecxpcNDcbvk QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn]
  - write old direct keys
writing keys: "/local/pins/direct/keys" []
  - write old indirect pins
INDIRECT PINS:  map[QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB:1 QmQ5vhrL7uv6tuoN9KeVBwd4PwfQkXdVVmDLUZuTNxqgvm:1 QmXgqKTbzdh83pQtKFb19SpMCpDDcKR2ujqk3pKph9aCNF:1 QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7:1 QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y:1 QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V:1 QmdrpEdSdqr2XsN2efU1wWJEMAa4KEiz2ZSnu8rnLBbFkn:1 QmejvEPop4D7YUadeGqYWmZxHhLc4JBUCzJJHWMzdcMe2y:1]
lowered version number to 2
===> Migration 3 to 2 succeeded!
===> Running migration 2 to 1...
ipfs migration:  migration 2 to 1 failed: rename T:\ipfs T:\ipfs: Access is denied.
```

**Comment by Stebalien** [comment]
@Sam3281 when did you last update go-ipfs?

**Comment by Sam3281** [comment]
@Stebalien My last update of go-ipfs is today

**Comment by djdv** [comment]
I looked into this a little and some of the early migration faults seem to be related to bugs that where fixed, but are retained via Godep versioning for the various migration methods.
Backporting critical fixes seems like the right thing to do in this case.

However, the bigger issue seems to be why your repo thinks it's v1.
Can you post more details about your version history, anything special about your configuration, etc.?

**Comment by Sam3281** [comment]
I try again by newest version, the bug occur by following steps:
1. Check out newest source code(check out today)
2. I got an error when make install 
![image](https://user-images.githubusercontent.com/49011306/56340663-281e7300-61e5-11e9-9680-2ab78c8809d0.png)
3. Then i edit the plugin\loader\preload.sh and add follow lines to that file. The compile is passed.
	pluginipldgit "github.com/ipfs/go-ipfs/plugin/plugins/git"
	pluginbadgerds "github.com/ipfs/go-ipfs/plugin/plugins/git"
	pluginflatfs "github.com/ipfs/go-ipfs/plugin/plugins/git"
	pluginlevelds "github.com/ipfs/go-ipfs/plugin/plugins/git" 
4. When i run "ipfs init", it show me "Error: unknown datastore type: flatfs"
5. After that i run "ipfs daemon", the error occur.

**Comment by djdv** [comment]
Those dependencies are included by default here: https://github.com/ipfs/go-ipfs/blob/master/plugin/loader/preload_list
so a build should succeed on unmodified master.
It may be best to run `git clean -fdx`, and check out the latest master again, making sure nothing has diverged from the source.

Using the MSYS2 setup here: https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md
results in a successful build and run for me on Windows 10 (1903). (https://github.com/ipfs/go-ipfs/commit/c3a7bc26607e15baca1a6ae4da358eff34a95f33)

If cleaning the source directory doesn't help, I'm curious what your build environment is like.
Where does your `git.exe`, `make.exe`, etc. come from?

**Comment by hsanjuan** [comment]
Closing as old and no updates from author, re-open as necessary
